<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Xdebug</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\$.*?)\s+(=)\s+(\S*)(\[.*\])</string>
			<key>name</key>
			<string>xdebug.output.context.object</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>string.quoted.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\$.*?)\s+(=)\s+(\(.*?\))\s(.*)</string>
			<key>name</key>
			<string>xdebug.output.context.property</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>variable.other.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>comment.line.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\$.*?)\s+(=)\s+(&lt;.*&gt;)</string>
			<key>name</key>
			<string>xdebug.output.context.unknown</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(\.{3,})</string>
			<key>name</key>
			<string>xdebug.output.context.trimmed</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.quoted.settings</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>comment.line.settings</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[\d+\])\s*(.*)(\..*)(\s*:.*?\d+)\s*(\((.*?):.*\)|$)</string>
			<key>name</key>
			<string>xdebug.output.stack.entry</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(\[.*?\])\s*(.*)</string>
			<key>name</key>
			<string>xdebug.output.stack.exception</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>comment.line.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(=&gt;)\s*(.*)</string>
			<key>name</key>
			<string>xdebug.output.breakpoint.file</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.anchor.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.settings</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>string.quoted.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*(?:(\|\+\|)|(\|-\|))\s*(\d+)\s*(?:(--)(.*)|.*)</string>
			<key>name</key>
			<string>xdebug.output.breakpoint.line</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.other.attribute-name.anchor.settings</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.settings</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>variable.other.settings</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.settings</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>string.quoted.settings</string>
				</dict>
				<key>7</key>
				<dict>
					<key>name</key>
					<string>support.type.settings</string>
				</dict>
				<key>8</key>
				<dict>
					<key>name</key>
					<string>variable.parameter.settings</string>
				</dict>
				<key>9</key>
				<dict>
					<key>name</key>
					<string>comment.line.settings</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^(?:(\|\+\|)|(\|-\|)|)\s+(\S*)\s+(?:(=)\s+(?:(\(.*?\))\s(.*)|(\S*)(\[.*\])|(&lt;.*&gt;))|.*)</string>
			<key>name</key>
			<string>xdebug.output.watch.entry</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>xdebug.output</string>
	<key>uuid</key>
	<string>924fce90-cf0a-4ef6-bf29-b98899924cad</string>
</dict>
</plist>
